# String
SOURCE_IPv6_ADDRESS = None
SOURCE_MAC = None
SENDING_IFACE = None
LISTENING_IFACE = None
DESTINATION_IPv6_ADDRESS = None

# Boolean
SOURCE_IPv6_ADDRESS_IS_MESSAGE_SENDABLE = None
SOURCE_IPv6_ADDRESS_IS_MESSAGE_RECEIVABLE = None
DESTINATION_IPv6_ADDRESS_IS_MESSAGE_SENDABLE = None
DESTINATION_IPv6_ADDRESS_IS_MESSAGE_RECEIVABLE = None

# Boolean
USE_ICMPv6 = None
USE_UDP = None
USE_TCP = None

# Float, ms
MEASURED_RTT = 50

# Float, %
MEASURED_PACKET_LOSS_RATE = 1

# Byte, 8 bytes
ENCRYPTION_DECRYPTION_KEY = b"12345728"